Features/inputs&buttons
lucy2n/ProCharity-project pull request #6
Opened 2023-04-08 21:50 UTC by Kukus89

2023-04-08 22:31 UTC, lucy2n requested changes
Нужно вынести папку blocks из pages в src. Итоговый путь должен быть таким `src/blocks`

2023-04-08 22:31 UTC, lucy2n commented on src/pages/blocks/input/input.css
> +  color: #7B878F;
Здесь нужно заменить цвет на `#374045`. Чтобы задать цвет `placeholder`'а нужно использовать псевдо-элемент `::placeholder`(https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder)

2023-04-09 07:31 UTC, Kukus89 commented on src/pages/blocks/input/input.css
> +  color: #7B878F;
вынес в псевдоэлементы

2023-04-09 09:17 UTC, lucy2n approved these changes

2023-04-09 09:18 UTC, merged